driver:
  name: vagrant
  provider: parallels
  server_name_prefix: "chef_pleroma"
  network:
    #- ["forwarded_port", {guest: 4000, host: 4000}]

provisioner:
  name: chef_zero
  product_version: <%= ENV['KITCHEN_CHEF_VER'] || 14 %>

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: freebsd-11
  - name: centos-7
  - name: debian-9

verifier:
  name: inspec
  reporter: junit

suites:
  - name: default-pleroma
    run_list:
      - recipe[pleroma_test]
